//POST http://localhost:3001/api/notes
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Fantsu kirja",
    "author": "lol",
    "url": "http://",
    "likes": 3
}

//{
//    "name": "Keimo Taalasmaa",
//    "number": "034-4292021"
//}

//{
//    "content": "VS Code Rest client is pretty good",
//    "important": false
//}
