//POST http://localhost:3001/api/notes
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Keimo Taalasmaa",
    "number": "034-4292021"
}
//{
//    "content": "VS Code Rest client is pretty good",
//    "important": false
//}
